apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-db
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: db
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/db

