apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-was
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  storageClassName: was
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/was

