apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web-login
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: web
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/web-login

